architecture: x86_64
config:
  raw.idmap: both 1000 1000
  security.nesting: "true"
devices:
  keys:
    path: /home/BLINCUSUSER/.ssh
    source: /home/BLINCUSUSER/.ssh
    type: disk
profiles:
- default
stateful: false
description: "No cloud-init"
