name: config
help: Manage Blincus config
footer: |
  View documentation online at https://blincus.dev

commands:
- name: list
  alias: l
  help: Show configuration values from ~/.config/blincus/config.ini
